CREATE TABLE STATION (STATION_ID INT PRIMARY KEY, STATION_NAME VARCHAR(255) NOT NULL)

CREATE TABLE TRAIN (TRAIN_ID INT PRIMARY KEY, TRAIN_NAME VARCHAR(255) NOT NULL)

CREATE TABLE STOP (STOP_ID INT PRIMARY KEY, STATION_ID INT NOT NULL, STOP_TIME TIME NOT NULL, STOP_PLATFORM VARCHAR(255) NOT NULL
 FOREIGN KEY STATION_ID REFERENCES STATION(STATION_ID))

CREATE TABLE TRAIN_STOP (TRAIN_ID INT, STOP_ID INT, PRIMARY KEY (TRAIN_ID, STOP_ID),
TRAIN_ID FOREIGN KEY REFERENCES TRAIN(TRAIN_ID), STOP_ID FOREIGN KEY REFERENCE STOP(STOP_ID))

CREATE PROCEDURE is_platform_free (IN t TIME, IN platform VARCHAR(255), OUT free BOOLEAN)
BEGIN
	SET free = (SELECT COUNT (*) FROM (SELECT * FROM STOP WHERE STOP_PLATFORM = platform AND STOP_TIME = t) > 0)
END
